# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    docker:
      - image: cimg/python:3.8  # You can change the Python version as needed
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python -m unittest discover
workflows:
  version: 2
  build_and_test:
    jobs:
      - build